FROM ubuntu:16.04
RUN apt-get update && apt-get install -y --force-yes golang
COPY src /src
COPY *.pem /
ENV GOPATH /
EXPOSE 6000
RUN go install github.com/ps/logservice
WORKDIR /
ENTRYPOINT ["./bin/logservice"]
